### ISSUE TITLE
Astreines Spiel... fast!

### ISSUE THREAD

**Issue by FabioWienerroither** [5ahmns-WiSem22-23/08-prj01-recap-bgreisberger#2]
Von den Funktionalitäten und den eigebauten Features ein tolles Spiel, allerdings fehlt mir das Theme: "Winter". 
Fehler sind mir beim Testen keine aufgefallen!

**Comment by bgreis** [comment]
Danke für den Issue Fabio Wienerroither!
Ich habe soeben meinen neuesten Stand gepusht. 
Das Winter Thema wurde aufgegriffen
Viel Spaß beim goomen ;-)
